global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ml4t'
    static_configs:
      - targets: ['ml4t:8050']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'monitoring'
    static_configs:
      - targets: ['monitoring:8051']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093' 